"""Generate original synthetic fixtures, not human-quality evaluation datasets."""
from __future__ import annotations
import argparse
import csv
from datetime import datetime,timedelta,timezone
import json
import math
from pathlib import Path
import wave
import numpy as np

EDGES = [(5,6),(5,7),(7,9),(6,8),(8,10),(5,11),(6,12),(11,12),(11,13),(13,15),(12,14),(14,16),(0,1),(0,2),(1,3),(2,4)]


def generate(root: Path, video=False):
    root.mkdir(parents=True,exist_ok=True)
    rng = np.random.default_rng(42)
    with (root/'workload.csv').open('w') as out:
        writer = csv.writer(out); writer.writerow(['timestamp','value'])
        for i in range(800):
            stamp = datetime(2024,1,1,tzinfo=timezone.utc)+timedelta(hours=i)
            value = 30 + .01*i + 8*math.sin(2*math.pi*i/24) + rng.normal(0,.5)
            writer.writerow([stamp.isoformat(),f'{value:.6f}'])
    with wave.open(str(root/'silence.wav'),'wb') as out:
        out.setnchannels(1); out.setsampwidth(2); out.setframerate(16000)
        out.writeframes(np.zeros(16000*3,dtype='<i2').tobytes())
    writer = None
    if video:
        import cv2
        writer = cv2.VideoWriter(str(root/'stickman.avi'),cv2.VideoWriter_fourcc(*'MJPG'),15,(640,480))
        if not writer.isOpened():
            raise RuntimeError('MJPG encoder unavailable')
    base = [[320,80],[310,76],[330,76],[300,80],[340,80],[285,145],[355,145],[260,210],[380,210],
            [245,270],[395,270],[295,270],[345,270],[280,355],[360,355],[270,440],[370,440]]
    try:
        with (root/'skeleton.jsonl').open('w') as out:
            out.write(json.dumps({'type':'metadata','schema_version':1,'skeleton':'coco-17','coordinates':'image-pixels',
                                  'fps':15,'synthetic':True,'license':'CC0-1.0','not_model_output':True})+'\n')
            for i in range(60):
                points = [[x+(12*math.sin(i/8) if j>6 else 0),y,1.0] for j,(x,y) in enumerate(base)]
                out.write(json.dumps({'type':'frame','index':i,'time_seconds':i/15,'width':640,'height':480,
                                      'people':[{'track_id':0,'joints':points}]})+'\n')
                if writer:
                    image = np.full((480,640,3),235,dtype=np.uint8)
                    for a,b in EDGES:
                        cv2.line(image,tuple(map(int,points[a][:2])),tuple(map(int,points[b][:2])),(40,40,40),5)
                    writer.write(image)
    finally:
        if writer:
            writer.release()
    (root/'PROVENANCE.txt').write_text('Original synthetic fixtures generated by recipes.samples, seed 42. CC0-1.0.\nSilence tests inference plumbing, not speech accuracy. Skeleton data tests replay, not pose detection.\n')


if __name__ == '__main__':
    p=argparse.ArgumentParser(description=__doc__); p.add_argument('--output-dir',type=Path,default=Path('runs/sample')); p.add_argument('--video',action='store_true')
    a=p.parse_args(); generate(a.output_dir,a.video); print(a.output_dir)
